version: '3.8'
services:
  backend:
    build: ./helpdesk-backend
    ports:
      - "8000:8000"
    volumes:
      - ./helpdesk-backend:/app
    depends_on:
      - database

  frontend:
    build: ./helpdesk-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./helpdesk-frontend:/app
    depends_on:
      - backend

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: helpdesk
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: